# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolkit" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "e9e0b32991a067ddf041c85a622702df8952be95fb6543f1760b2602e6d91598"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6e914f8dcdd4e6d43273146c8d28517ef84a5aeeacd40f198425ec464df5afc"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7630b185c3121f083c11ca20010b8e3c240f18d928037a687d79e42a9288e36"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4d551cd588d4dd8f7f89edc23ecef2bc5755b5963a82378a3e43dba69d1b2c2"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "toolkit"
  desc "Toolkit CLI: cross-platform command-line tool for cloud and infrastructure automation"
  homepage "https://github.com/jingle2008/toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolkit"

  # No zap stanza required

end
