# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolkit" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "259f00df79077661b0983cd2bdaa37d7f60f0e1fe8326ddfecfc15618fe3b121"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1cb6d37c9f680b11aae2f7b4515af4e70c74520e365261afc64f2b4a447c05b"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c595d1b18359a4e416f8efd7e2e299c3469969941f42751294fd2d10f83ecefa"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a951b1eb9fa5e5dfb7ba42ad5a9e5ac43c3ae3014c54b29269d160cab728da5"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "toolkit"
  desc "Toolkit CLI: cross-platform command-line tool for cloud and infrastructure automation"
  homepage "https://github.com/jingle2008/toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolkit"

  # No zap stanza required
end
