# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolkit" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "c7727ced2da83162a6b6e05bec124c2391e41404198c07f8ce385c64e5390263"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc544b98198d770496d23e845b44906f86d21dcb3f3fe45f1dc75134697de6ff"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58eaef9bd36f9b5186e943e917853f08519a8c9c8bfb789d2acf435424bdc1ba"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff47f558b2269ec4fe033c6539bff608eb442283b0ca1b4b38a21f40977a6a71"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "toolkit"
  desc "Toolkit CLI: cross-platform command-line tool for cloud and infrastructure automation"
  homepage "https://github.com/jingle2008/toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolkit"

  # No zap stanza required

end
