# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolkit < Formula
  desc "Toolkit CLI: cross-platform command-line tool for cloud & infra automation"
  homepage "https://github.com/jingle2008/toolkit"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.8.0/toolkit_0.8.0_darwin_amd64.tar.gz"
      sha256 "c5f80295aa7d92ac3a8f153376ff99aa3d25c7ceec461a34ddf87486def70656"

      define_method(:install) do
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.8.0/toolkit_0.8.0_darwin_arm64.tar.gz"
      sha256 "e1aa1bb92f91eb79cfce15e1a1bd3d3fb5eb6d012f8b227ff545615851b0deef"

      define_method(:install) do
        bin.install "toolkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.8.0/toolkit_0.8.0_linux_amd64.tar.gz"
      sha256 "fa18ea77a43230732cf030ea116838ce69482e8e226b84712037861378e24fb4"
      define_method(:install) do
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.8.0/toolkit_0.8.0_linux_arm64.tar.gz"
      sha256 "56f2f8b80690f44a8188ef3d08475e04077ffe384f5d981b25cc70d816d8122d"
      define_method(:install) do
        bin.install "toolkit"
      end
    end
  end

  test do
    system "#{bin}/toolkit", "version"
  end
end
