# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolkit < Formula
  desc "Toolkit CLI: cross-platform command-line tool for cloud & infra automation"
  homepage "https://github.com/jingle2008/toolkit"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.7.0/toolkit_0.7.0_darwin_amd64.tar.gz"
      sha256 "139bb164fc91076bd5954487af29316ce2fb1134b23f95846672df417c3272d7"

      define_method(:install) do
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.7.0/toolkit_0.7.0_darwin_arm64.tar.gz"
      sha256 "163f261d1285714f26299eeeb2fb513309e4c748ce2502570c955002e11d93c9"

      define_method(:install) do
        bin.install "toolkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.7.0/toolkit_0.7.0_linux_amd64.tar.gz"
      sha256 "fc63edee9b79ffa137b0978866c43d9cb8c1d66f5228a413a7e2cffc55b1445d"
      define_method(:install) do
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.7.0/toolkit_0.7.0_linux_arm64.tar.gz"
      sha256 "37ad1dbb797c0dbe615f23f6bdc00b081159bf8ec5185ebc20082f233a8ef1fc"
      define_method(:install) do
        bin.install "toolkit"
      end
    end
  end

  test do
    system "#{bin}/toolkit", "version"
  end
end
